config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :categoria
  resources :articulos
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: %i[ show edit update destroy ]

  # GET /categoria or /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1 or /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria or /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: "Categorium was successfully created." }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1 or /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: "Categorium was successfully updated." }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1 or /categoria/1.json
  def destroy
    @categorium.destroy!

    respond_to do |format|
      format.html { redirect_to categoria_path, status: :see_other, notice: "Categorium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categorium_params
      params.require(:categorium).permit(:nombre, :descripcion)
    end
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/views/categoria/_categorium.html.erb
<div id="<%= dom_id categorium %>">
  <p>
    <strong>Nombre:</strong>
    <%= categorium.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= categorium.descripcion %>
  </p>

</div>

app/views/categoria/_form.html.erb
<%= form_with(model: categorium) do |form| %>
  <% if categorium.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
        <% categorium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categoria/edit.html.erb
<% content_for :title, "Editing categorium" %>

<h1>Editing categorium</h1>

<%= render "form", categorium: @categorium %>

<br>

<div>
  <%= link_to "Ver categoria", @categorium %> |
  <%= link_to "Regresar a categoria", categoria_path %>
</div>

app/views/categoria/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categoria" %>

<h1>Categoria</h1>

<div id="categoria">
  <% @categoria.each do |categorium| %>
    <%= render categorium %>
    <p>
      <%= link_to "Ver categoria", categorium %>
    </p>
  <% end %>
</div>

<%= link_to "Nueva categoria", new_categorium_path, class: "new-resource-link" %> |
<%= link_to "Ir a comentarios", comentarios_path, class: "extra-links" %> 

app/views/categoria/new.html.erb
<% content_for :title, "New categorium" %>

<h1>Nueva categoria</h1>

<%= render "form", categorium: @categorium %>

<br>

<div>
  <%= link_to "Regresar a categoria", categoria_path %>
</div>

app/views/categoria/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @categorium %>

<div>
  <%= link_to "Editar categoria", edit_categorium_path(@categorium) %> |
  <%= link_to "Lista de categoria", categoria_path %>

  <%= button_to "Eliminar categoria", @categorium, method: :delete %>
</div>